name: Python CI

on:
  push:
    branches:
      - unit-testing   # Ensures that the CI will run on the unit-testing branch
  pull_request:
    branches:
      - unit-testing   # Ensures the CI runs on pull requests to the unit-testing branch
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.12]  # Specifies Python version to use

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v4  # Sets up the Python environment
        with:
          python-version: ${{ matrix.python-version }}  # Use the specified Python version from the matrix

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install any dependencies from the requirements.txt file
          
      - name: Run tests
        run: |
          python -m pytest unit-testing/all_test.py  # Run the Pytest tests from the all_test.py file